#spring.datasource.url= jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=password

datasource:
  url: jdbc:postgresql://localhost:5432/postgres
#  driver-class-name:
  username: postgres
  password: password
